version: '3'

services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.db
    networks:
      - network

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    depends_on:
      - mysql
    networks:
      - network
    ports:
      - "8080:80"

networks:
  network:
